kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
  
trigger:
  branch:
    exclude:
    - master
    - main

---
kind: pipeline
name: mysql

steps:
- name: print-mysql-password
  image: alpine:latest
  environment:
    - from_secret: mysql_password
  commands:
  - echo mysql_password

trigger:
  branch:
    exclude:
    - master
    - main