---
kind: pipeline
type: docker
name: hello-world
steps:
- name: docker
 image: ghcr.io/tekendra-timsina/hello-world:latest
 settings:
   repo: tekendra-timsina/hello-world
   username:
     from_secret: github_username
   password:
     from_secret: github_token
   tags:
     - latest
