# kind: pipeline
# name: python0

# steps:
# - name: test
#   image: python
#   commands:
#   - pip install -r requirements.txt
#   - pytest

# ---
kind: pipeline
name: python1

steps:
- name: print-mysql-password
  image: alpine:latest
  environment:
    ANOTHER_MYSQL_PASSWORD:
      from_secret: my_secrets
  commands:
  - apk update && apk add jq
  - apk add --update coreutils
  - apk add python3
  - echo "export $ANOTHER_MYSQL_PASSWORD" > myfile.json
  - cat myfile.json
  - python3 parse.py

trigger:
  branch:
  - main
  - testi