kind: pipeline
name: python0

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest

---
kind: pipeline
name: python1

steps:
- name: print-mysql-password
  image: alpine:latest
  environment:
    ANOTHER_MYSQL_PASSWORD:
      from_secret: ANOTHER_MYSQL_PASSWORD
  commands:
  - apk update && apk add jq
  - apk add --update coreutils
  - apk add python3
  - echo $ANOTHER_MYSQL_PASSWORD
  - mkdir /run/secrets/
  - echo -n "$ANOTHER_MYSQL_PASSWORD" > /run/secrets/myfile.json
  - python3 parse.py
