kind: pipeline
type: docker
name: python1

steps:
- name: print-mysql-password
  image: alpine:latest
  environment:
    ANOTHER_MYSQL_PASSWORD:
      from_secret: my_secrets
    TEST_SECRET:
      from_secret: testsecret
    TEST_SECRET_2:
      from_secret: another_test_secret
  commands:
  - apk update && apk add jq
  - apk add --update coreutils
  - apk add python3
  - python3 parse.py
  - cat settings.json

trigger:
  branch:
  - testing_branch
  - main
