kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
  
trigger:
  branch:
    exclude:
    - master
    - main

---
kind: pipeline
name: mysql

steps:
- name: print-mysql-password
  image: alpine:latest
  environment:
    MYSQL_PASSWORD:
      from_secret: mysql_password
  commands:
  - echo $MYSQL_PASSWORD

trigger:
  branch:
    exclude:
    - master
    - main

---
kind: pipeline
name: mysql2

steps:
- name: print-mysql-password
  image: alpine:latest
  environment:
    ANOTHER_MYSQL_PASSWORD:
      from_secret: settings
  commands:
  - echo $ANOTHER_MYSQL_PASSWORD > myfile.txt
  - cat myfile.txt

trigger:
  branch:
    exclude:
    - master
    - main
