kind: pipeline
name: python0

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest

---
kind: pipeline
name: python1

steps:
- name: print-mysql-password
  image: alpine:latest
  environment:
    ANOTHER_MYSQL_PASSWORD:
      from_secret: my_settings
  commands:
  - apk update && apk add jq
  - apk add python3
  - echo ANOTHER_MYSQL_PASSWORD | base64 --decode > myfile.json
  - echo mydile.json
  - python3 parse.py
