kind: pipeline
type: docker
name: python1

steps:
- name: print-mysql-password
  image: alpine:latest
  environment:
    TEST_SECRET:
      from_secret: testsecret
  commands:
    [
      "apk update && apk add jq",
      "apk add --update coreutils",
      "mkdir -p /run/secrets",
      'echo {"TEST_SECRET" : "$TEST_SECRET"} > /run/secrets/settings.json',
      "cat /run/secrets/settings.json"
  ]

  - 
  - 
 

trigger:
  branch:
  - testing_branch
  - main
